version: "3"

services:
  # The Cookie Factory backend in SpringBoot
  teamh-server:
    image: teamh-backend
    container_name: server
    environment:
      - BANK_WITH_PORT=bank-system:9090
      - POSTGRES_HOST=postgres:5432
    # waiting for postgres
    entrypoint: "bash -c '/opt/app/wait-for-it.sh $${POSTGRES_HOST} -- java -jar /opt/app/app.jar --bank.host.baseurl=http://$${BANK_WITH_PORT}'"
    depends_on:
      - bank-system
      - postgres


  # the postgres DB to be connected to the backend (watch out: no volume specified, everything can be lost)
  postgres:
    image: postgres:15.2
    container_name: db
    environment:
      - POSTGRES_PASSWORD=postgrespass
      - POSTGRES_USER=postgresuser
      - POSTGRES_DB=tcf-db
    ports:
      - "8003:5432"


  # A simple java CLI
  teamh-cli:
    image: teamh-cli
    container_name: cli
    environment:
      - SERVER_WITH_PORT=teamh-server:8080
    entrypoint: "bash -c '/opt/app/wait-for-it.sh $${SERVER_WITH_PORT} -- java -jar /opt/app/app.jar'"
    depends_on:
      - teamh-server
    volumes:
      - ./cli/scripts/demo.txt:/opt/app/demo.txt
      - ./cli/scripts/register.txt:/opt/app/register.txt
      - ./cli/scripts/settled-payment.txt:/opt/app/settled-payment.txt
      - ./cli/scripts/fidelity-payment.txt:/opt/app/fidelity-payment.txt
      - ./cli/scripts/discount-payment.txt:/opt/app/discount-payment.txt
      - ./cli/scripts/full-payment-scripts.txt:/opt/app/full-payment-scripts.txt
    stdin_open: true
    tty: true

  # An external bank service in NestJs
  bank-system:
    image: teamh-bank
    container_name: bank